services:
    via-bot:
        build: .
        container_name: Via-bot
        restart: unless-stopped
        env_file:
            - ./qq.env
        volumes:
            - ./:/app
        command: python via.py

    support_bot:
        build: .
        container_name: Support-bot
        restart: unless-stopped
        env_file:
            - ./qq.env
        volumes:
            - ./:/app
        command: python support.py
    web:
        image: nginx:alpine
        container_name: Via-web
        restart: unless-stopped
        env_file:
            - ./qq.env
        environment:
            - DOMAIN_NAME=$${DOMAIN#*://}
        volumes:
          - ./web:/usr/share/nginx/html
          - ${CERT_PATH}:/etc/nginx/ssl:ro
          - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
        ports:
            - "80:80"
            - "443:443"
