services:
    vpn-bot:
        build: .
        container_name: vpn-bot
        restart: unless-stopped
        env_file:
            - ./qq.env
        volumes:
            - ./:/app
        command: python vpn.py

    support_bot:
        build: .
        container_name: support-bot
        restart: unless-stopped
        env_file:
            - ./qq.env
        volumes:
            - ./:/app
        command: python support.py
    web:
        image: nginx:alpine
        container_name: vpn-web
        restart: unless-stopped
        env_file:
            - ./qq.env
        volumes:
            - ./web:/usr/share/nginx/html
            - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
            - /root/cert/my-via.ru:/etc/nginx/ssl:ro
        command: |
            /bin/sh -c "
            export DOMAIN=$(echo $$DOMAIN | sed -e 's|^https://||' -e 's|^http://||' -e 's|/$$||');
                printf 'window.APP_CONFIG = {\n  SUPPORT_BOT_URL: \"%s\",\n  MAIN_BOT_URL: \"%s\",\n  SITE_NAME: \"%s\",\n  SITE_FULL: \"%s\"\n};\n' \"$${SUPPORT_BOT_URL}\" \"$${MAIN_BOT_URL}\" \"$${SITE_NAME}\" \"$${SITE_FULL}\" > /usr/share/nginx/html/env-config.js
            exec /docker-entrypoint.sh nginx -g 'daemon off;'
            "
        ports:
            - "80:80"
            - "443:443"
